#### NumPy - Basic Operations

##### Mathematical Operations

In [1]:
import numpy as np

In [2]:
#addition
np.add(45,20)

65

In [3]:
#subtraction
np.subtract(45,23)

22

In [4]:
# ndarray multiplication
# create ndarray which conntains number of hrs worked for 5 days
# hourly rate is 15 USD
np_daily_wage = np.array([7,9,13,8,11])*15

In [5]:
#total earning after 5 days
#use sum method to add all data elements of ndarray
sum(np_daily_wage)

720

In [6]:
#print hourly wage for each day
print (np_daily_wage)

[105 135 195 120 165]


In [7]:
np_daily_wage

array([105, 135, 195, 120, 165])

##### Comparison Operations

In [8]:
#comparison operations
#create ndarray for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([23,41,55,47,38])

In [9]:
#week with more than 40 hrs 
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [10]:
#week with hrs not equals to 40
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

##### Logical Operations

In [11]:
#Logical AND operation
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [12]:
#Logical NOT operation
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

In [1]:
#not using numpy
weeklydur = [23,41,55,47,38]
seldur = []
for i in weeklydur:
    if i>40:
        seldur.append(i)

In [2]:
print(seldur)

[41, 55, 47]


In [3]:
#using lambda
seldur = list(filter(lambda n: n>40,weeklydur))
print(seldur)

[41, 55, 47]
