In [2]:
#import NumPy library
import numpy as np

In [3]:
#first NumPy arrayp
first_numpy_array = np.array([1,2,3,4])

In [4]:
#print first array
print first_numpy_array

[1 2 3 4]


In [5]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[  1.88482645e-316,   2.55444508e-316,   2.09919481e-316],
       [  2.55446405e-316,   2.55447117e-316,   1.88513356e-316]])

In [8]:
#array with arange method
np_arange = np.arange(12)

In [9]:
#print array
print np_arange

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
#reshape method to change/ create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
#linspace for linearly (equal) spaced data elements
np_linspce = np.linspace(1,6,5)

In [12]:
#print linespaced array
print np_linspce

[ 1.    2.25  3.5   4.75  6.  ]


In [13]:
#One dimensional array
oneD_array = np.arange(15)

In [14]:
#print 1D array
print oneD_array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
#Two dimensional array
TwoD_array = oneD_array.reshape(3,5)

In [16]:
#print 2D array
print TwoD_array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
#Three dimensional array
ThreeD_array = np.arange(27).reshape(3,3,3)

In [18]:
#Print 3D array
print ThreeD_array

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
