In [1]:
import numpy as np

## Problem 1

In [2]:
distance = [10,15,17,24]
time = [.30,.47,.55,1.20]

In [3]:
np_time = np.array(time)

In [5]:
for i in np_time:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [6]:
time2 = [100,.30,.47,.55,1.20]   
np_time2 = np.array(time2)

In [7]:
for i in np_time2:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [8]:
np_distance = np.array(distance)
speed = np_distance/np_time
print(speed)

[33.33333333 31.91489362 30.90909091 20.        ]


## Problem 2

In [9]:
first_trial_cyclist = [10,15,17,24]
second_trial_cyclist = [12,11,21,24]

In [10]:
np_first_trial_cyclist = np.array(first_trial_cyclist)
np_second_trial_cylist = np.array(second_trial_cyclist)

In [11]:
result = np_first_trial_cyclist+np_second_trial_cylist

In [12]:
print(result)

[22 26 38 48]


In [13]:
trials_new = np.array([first_trial_cyclist,second_trial_cyclist])

In [14]:
print(trials_new)

[[10 15 17 24]
 [12 11 21 24]]


In [15]:
trials_new.ndim

2

In [16]:
trials_new.dtype

dtype('int32')

In [17]:
trials_new[1:]

array([[12, 11, 21, 24]])

In [18]:
trials_new[:]

array([[10, 15, 17, 24],
       [12, 11, 21, 24]])

In [19]:
trials_new[:,0]

array([10, 12])

In [20]:
trials_new[:,1:3]

array([[15, 17],
       [11, 21]])

In [21]:
trials_new[:,1:3].shape

(2, 2)

In [22]:
for n in trials_new[1:]:
    for j in n:
         print(j,n)

12 [12 11 21 24]
11 [12 11 21 24]
21 [12 11 21 24]
24 [12 11 21 24]


In [23]:
for n in trials_new:
    print(n)

[10 15 17 24]
[12 11 21 24]


In [24]:
for n in trials_new:
    for j in n:
         print(j,n)

10 [10 15 17 24]
15 [10 15 17 24]
17 [10 15 17 24]
24 [10 15 17 24]
12 [12 11 21 24]
11 [12 11 21 24]
21 [12 11 21 24]
24 [12 11 21 24]


In [25]:
trials_sel = trials_new>17

In [26]:
print(trials_sel)

[[False False False  True]
 [False False  True  True]]


In [27]:
trials_self = trials_new[trials_sel]

In [28]:
trials_self

array([24, 21, 24])

## Broadcasting

In [29]:
array_a = np.array([2,34,5,8])
array_b = np.array([.3,.3,.3,.3])

In [30]:
result = array_a * array_b
print(result)

[ 0.6 10.2  1.5  2.4]


In [31]:
#variable with a scalar value
scalar_c = 0.3

In [32]:
#multiple array with scalar value
result2 = array_a * scalar_c
print(result2)

[ 0.6 10.2  1.5  2.4]


## Problem 3

In [34]:
countries = np.array(['luxembourg','Norway','Japan','Switzerland','USA'])
gdp_per_capita = np.array([52056.1234,40345.4565,45456.78564,33245.56782,34544.45888])

In [35]:
#max gdp per capita (shows index position)
max_gdp_per_capita = gdp_per_capita.argmax()
print(max_gdp_per_capita)

0


In [36]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]
print(country_with_max_gdp_per_capita)

luxembourg


In [37]:
min_gdp_per_capital = gdp_per_capita.argmin()
print(min_gdp_per_capital)

3


In [38]:
country_with_min_gdp_per_capita = countries[min_gdp_per_capital]
print(country_with_min_gdp_per_capita)


Switzerland


In [39]:
#printing values iteratively
for country in countries:
    print('ecalculating country {}'.format(country))

ecalculating country luxembourg
ecalculating country Norway
ecalculating country Japan
ecalculating country Switzerland
ecalculating country USA


In [40]:
#using formating
for i in range(0,len(countries)-1):
    country = countries[i]
    country_gdp_per_capita = gdp_per_capita[i]
    print('country {} per capita gdp is {}'.format(country,country_gdp_per_capita))

country luxembourg per capita gdp is 52056.1234
country Norway per capita gdp is 40345.4565
country Japan per capita gdp is 45456.78564
country Switzerland per capita gdp is 33245.56782


In [41]:
print(gdp_per_capita.max())
print(gdp_per_capita.min())
print(gdp_per_capita.mean())
print(gdp_per_capita.std())

52056.1234
33245.56782
41129.678448
6989.282898226141


In [42]:
#Using other functions
marks = np.array([[23,34,45,56],[23,23,34,67]])

In [43]:
marks

array([[23, 34, 45, 56],
       [23, 23, 34, 67]])

In [44]:
marks.transpose()

array([[23, 23],
       [34, 23],
       [45, 34],
       [56, 67]])

In [45]:
marks.reshape(4,2)

array([[23, 34],
       [45, 56],
       [23, 23],
       [34, 67]])

In [46]:
marks

array([[23, 34, 45, 56],
       [23, 23, 34, 67]])

In [47]:
from numpy import linalg
np.linalg.inv(marks)

LinAlgError: Last 2 dimensions of the array must be square

In [48]:
marks = np.array([[23,34],[23,23]])

In [49]:
from numpy import linalg
np.linalg.inv(marks)

array([[-0.09090909,  0.13438735],
       [ 0.09090909, -0.09090909]])

In [50]:
np.trace(marks)

46